apiVersion: v1
kind: Secret
metadata:
  name: aivar-backend-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded connection string
  # Echo -n "postgresql+asyncpg://postgres:password@host:5432/postgres" | base64
  DATABASE_URL: "cG9zdGdyZXNxbCthc3luY3BnOi8vcG9zdGdyZXM6YmFzZTY0cGxhY2Vob2xkZXJAdGVzdC1kYi5zdXBhYmFzZS5jbyc6NTQzMi9wb3N0Z3Jlcw=="
